repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args:
          - -L
          - HASS,hass,Hass
          - --skip
          - "uv.lock,*.map"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        files: "^(mqtt_entity)/"
        #exclude: "x/x.py"
        additional_dependencies: ["attrs"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: uv
        language: system
        types: [python]
        pass_filenames: false
        args:
          - run
          - pylint
          - src
          - tests
          - -rn # Only display messages
          - -sn # Don't display the score