name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "www/**"
      - ".github/workflows/deploy.yml"

defaults:
  run:
    working-directory: www

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # - uses: dorny/paths-filter@v2
      #   id: changes
      #   with:
      #     filters: |
      #       www:
      #         - www/**
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run docs:build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          # external_repository: labctl/labctl
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: www/docs/.vitepress/dist
